### ISSUE TITLE
Incorrect File URL Generation When Using UseTestEnvironment

### ISSUE THREAD

**Issue by esklo** [PaulSonOfLars/gotgbot#101]
# Description 

When the UseTestEnvironment flag is enabled, the generated URL does not account for this flag, leading to incorrect URL being produced.

# Steps to Reproduce

1. Enable the UseTestEnvironment flag in the bot.
2. Attempt to generate a file download URL using the GetURL method.
https://github.com/PaulSonOfLars/gotgbot/blob/12b2834a2677e5a225660d1c8f6c40cc2fc21a7c/custom_helpers.go#L51-L53

# System information:

- Library version: v2.0.0-rc.20

**Comment by PaulSonOfLars** [comment]
Hi, thank you for the report!

This is definitely a bug in the lib - I'll have a look at it and fix it asap.

**Comment by PaulSonOfLars** [comment]
Should be fixed in the next release - got a couple of other things to get merged first but should hopefully be soon!

**Comment by PaulSonOfLars** [comment]
All done as of v2.0.0-rc.21!
