### ISSUE TITLE
Add `Parameters` in `TelegramError`

### ISSUE THREAD

**Issue by liuerfire** [PaulSonOfLars/gotgbot#106]
https://github.com/PaulSonOfLars/gotgbot/blob/v2.0.0-rc.20/request.go#L173-L185

It seems there's no way to access [`Parameters`](https://github.com/PaulSonOfLars/gotgbot/blob/v2.0.0-rc.20/request.go#L57)?

**Comment by PaulSonOfLars** [comment]
Thanks for reporting, and thank you for the PR!
