### ISSUE TITLE
Need sample codes on how to attach a video/gif/photo to the top of a message (`bot.SendMessage()`)

### ISSUE THREAD

**Issue by theghostmac** [PaulSonOfLars/gotgbot#164]

**Comment by PaulSonOfLars** [comment]
A helpful place to start may be to get familiar with the bot API spec first, so you know which methods to use for media: https://core.telegram.org/bots/api#sendvideo

**Comment by PaulSonOfLars** [comment]
Closing due to lack of response, assuming solved
