### ISSUE TITLE
Adding a handler for a NewPreCheckoutQuery - no precheckoutquery.All option

### ISSUE THREAD

**Issue by svscorp** [PaulSonOfLars/gotgbot#172]
# Description of the problem / feature request

I am trying to add a handler for PreCheckoutQuery. When I do it for a Callback, this is the syntax:
`dispatcher.AddHandler(handlers.NewCallback(callbackquery.All, processCallbackQuery))`

however, for a PreCheckoutQuery, I'd expect something like 

`dispatcher.AddHandler(handlers.NewPreCheckoutQuery(precheckoutquery.All, processPreCheckoutQuery))`

but I didn't find it. Instead, I found 2 `shippingquery.All` - one, for ShippingQuery itself, which seems legit. 2nd is for PreCheckoutQuery, but under package ShippingQuery

![Screenshot 2024-07-03 at 16 49 27](https://github.com/PaulSonOfLars/gotgbot/assets/475464/7429a0a8-86b0-41fa-9435-acfd571ae6ed)

**Comment by PaulSonOfLars** [comment]
Hey, thanks for reporting; looks like that was a copypasta mistake with package names. Should be fixed in #173, if youd like to give that try!

You can probably tell that my bots don't use payments...

**Comment by svscorp** [comment]
Tested against the branch of #173 All works!

**Comment by svscorp** [comment]
@PaulSonOfLars no worries, as a community we help :)

> You can probably tell that my bots don't use payments...
I tested, payments via CC and Stars work End to End.

**Comment by svscorp** [comment]
@PaulSonOfLars  can you please create a new tag for go.mod? Otherwise I have to hook to the branch, and now a previous version (without this change) is available only: v2.0.0-rc.28

**Comment by PaulSonOfLars** [comment]
I'm not going to cut a new release for a change with such a narrow impact and which can easily be fixed by pinning to a new commit. There are a few other changes I'd like to make before a next version.

If you urgently need the latest changes, you can pin to the commit you need by using `go get <module>@<commit hash>`

**Comment by svscorp** [comment]
Yes, that's what I using. Okay. Clear.
