### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by pd5200** [PaulSonOfLars/gotgbot#178]
I hope the go get -u command can retrieve the most recently modified version, but currently it always gets the latest tagged version. I hope to fix this, so that if there is no new tag created, it can directly update to the latest commit, so that users can directly use the latest version when updating the code, without needing too many extra operations.

**Comment by JasonKhew96** [comment]
Please read `go get` doc, there is a reason why the latest commit is not tagged yet.
 https://github.com/PaulSonOfLars/gotgbot/issues/167#issuecomment-2198512088

https://go.dev/ref/mod#go-get
https://go.dev/ref/mod#version-queries


```
go get github.com/PaulSonOfLars/gotgbot/v2@hash
```
