### ISSUE TITLE
unable to create new updater: invalid getMe request

### ISSUE THREAD

**Issue by Roker2** [PaulSonOfLars/gotgbot#2]
Hi! I got API key for TG bot, download your bot sample, put my API key. I got this error
`unable to create new updater: invalid getMe request`
How to resolve it?

**Comment by PaulSonOfLars** [comment]
Looks like you're not using the right API key, or using it wrong.

**Comment by Roker2** [comment]
So. If I put key to
https://github.com/PaulSonOfLars/gotgbot/blob/883066135bc64563a3730413530c31c79be7df94/sampleBot/bot.go#L20
bot is not working. If I put key to
https://github.com/PaulSonOfLars/gotgbot/blob/883066135bc64563a3730413530c31c79be7df94/sampleBot/bot.go#L22
as string, bot is working.
Thank you for helping, I really didn't put one part of key.
I use Manjaro Cinnamon.

**Comment by PaulSonOfLars** [comment]
As a sidenote: `os.Getenv` was looking at the environment variable named TOKEN. If i understand right, you replaced "TOKEN" with your token; which would not have worked.
