### ISSUE TITLE
Does not include parameters which their values are an empty string in requests

### ISSUE THREAD

**Issue by rojvv** [PaulSonOfLars/gotgbot#25]
# Description of the problem / feature request

gotgbot does not include parameters which their values are an empty string (`""`) in the request being sent to Telegram, meanwhile some parameters can be empty strings, for example: `switch_inline_query` & `switch_inline_query_current_chat` when sending a message.

# Bugs

This code tries to send a message with a switch inline button with a parameter with an empty value, but as mentioned, gotgbot ignores the parameter with the empty value and just includes the text parameter, and causes the following error: `Bad Request: can't parse inline keyboard button: Text buttons are unallowed in the inline keyboard`.

```go
package main

import (
	"github.com/PaulSonOfLars/gotgbot/v2"
	"github.com/PaulSonOfLars/gotgbot/v2/ext"
	"github.com/PaulSonOfLars/gotgbot/v2/ext/handlers"
	"net/http"
)

func main() {
	b, err := gotgbot.NewBot("BOT_TOKEN", &gotgbot.BotOpts{
		Client:      http.Client{},
		GetTimeout:  gotgbot.DefaultGetTimeout,
		PostTimeout: gotgbot.DefaultPostTimeout,
	})
	if err != nil {
		panic(err)
	}
	updater := ext.NewUpdater(nil)
	dispatcher := updater.Dispatcher
	dispatcher.AddHandler(handlers.NewCommand("start", func(b *gotgbot.Bot, ctx *ext.Context) error {
		ctx.EffectiveMessage.Reply(
			b,
			".",
			&gotgbot.SendMessageOpts{
				ReplyMarkup: gotgbot.InlineKeyboardMarkup{
					InlineKeyboard: [][]gotgbot.InlineKeyboardButton{
						{
							gotgbot.InlineKeyboardButton{
								Text:              ".",
								SwitchInlineQuery: "",
							},
						},
					},
				},
			})
		return nil
	}))
	err = updater.StartPolling(b, &ext.PollingOpts{DropPendingUpdates: true})
	if err != nil {
		panic(err)
	}
	updater.Idle()
}
```

# System information:

- Output of `go version`: v1.16.4
- Library version (as seen in `go.mod` file): v2.0.0-beta9.0.20210524185244-d0297001844d

**Comment by PaulSonOfLars** [comment]
Hi, and thanks for raising an issue!

I've made some changes, and this should be fixed by #31.
