### ISSUE TITLE
question: Don't work on heroku

### ISSUE THREAD

**Issue by Roker2** [PaulSonOfLars/gotgbot#4]
Hi! I adapted program for webhooks and it doesn't work.
[My commit](https://github.com/Roker2/RockBot/commit/6904ea8c8d85e98559bc602ccacf316f05a54bf7).
So... I installed webhook.
`https://api.telegram.org/botBOT_TOKEN/setWebhook?url=https://calm-cove-01177.herokuapp.com/BOT_TOKEN`
I got `"last_error_message":"Wrong response from the webhook: 503 Service Unavailable","max_connections":40`
I see this in logs
`2020-03-17T10:31:01.929783+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/BOT_TOKEN" host=calm-cove-01177.herokuapp.com request_id=11ab7aec-5bdb-4a55-900d-9dd87844f834 fwd="91.108.6.99" dyno= connect= service= status=503 bytes= protocol=https`
I don't have any idea how to fix it.

**Comment by PaulSonOfLars** [comment]
Unrelated to gotgbot, but I think your issue is with your `os.getenv`. Are you sure your environment variable starts with a /?

**Comment by Roker2** [comment]
I don't use os.getenv, bot get token from json (and yes, I uploaded it, I created another brunch with my json).
https://github.com/Roker2/RockBot/blob/6904ea8c8d85e98559bc602ccacf316f05a54bf7/main.go#L39

**Comment by PaulSonOfLars** [comment]
https://github.com/Roker2/RockBot/blob/6904ea8c8d85e98559bc602ccacf316f05a54bf7/main.go#L79

Yes, you do

**Comment by Roker2** [comment]
Oh, yes, sorry. I copyed without thinking.
What is the URL? URL of heroku program like `https://calm-cove-01177.herokuapp.com`?

**Comment by PaulSonOfLars** [comment]
Yes. That url is all you need. 
And there's no need to put the token suffix after, that's done already.

**Comment by Roker2** [comment]
Hm, it doesn't work, I added my URL and it didn't help.
https://github.com/Roker2/RockBot/blob/640f57dac0c174043c27c9dc5c52d2370d3a7dcc/main.go#L79

**Comment by Roker2** [comment]
Maybe need I to set up something in heroku settings?

**Comment by PaulSonOfLars** [comment]
"didn't work" isn't a particularly helpful debug log. And yes, you need to be sure you're using Web workers with heroku. Maybe more, idk, not familiar. 

With all due respect, since we've established this isn't a library problem, do you have anything against closing this issue?

**Comment by Roker2** [comment]
`time="2020-03-17T13:19:04Z" level=fatal msg="Failed to start bot due to: failed to set webhook: unable to execute GET request to setWebhook: Get https://api.telegram.org/botBOT_TOKEN/setWebhook?allowed_updates=%5B%5D&max_connections=40&url=https%3A%2F%2Fcalm-cove-01177.herokuapp.com%2FFIRST_PART_OF_TOKEN%3ASECOND_PART_OF_TOKEN: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" error="failed to set webhook: unable to execute GET request to setWebhook: Get https://api.telegram.org/botBOT_TOKEN/setWebhook?allowed_updates=%5B%5D&max_connections=40&url=https%3A%2F%2Fcalm-cove-01177.herokuapp.com%2FFIRST_PART_OF_TOKEN%3ASECOND_PART_OF_TOKEN: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"`



> With all due respect, since we've established this isn't a library problem, do you have anything against closing this issue?

No, you can close.
