### ISSUE TITLE
Error: Unexpected end of JSON input in webhook mode

### ISSUE THREAD

**Issue by Roker2** [PaulSonOfLars/gotgbot#8]
Hi! I updated you package and got this error in logs:

level=info msg="Starting webhook"
level=fatal msg="Failed to start bot due to: unexpected end of JSON input" error="unexpected end of JSON input"

If bot use Long Polling mode, it work without any errors.

**Comment by Roker2** [comment]
So, I removed this commit and bot work again in webhook mode.
https://github.com/PaulSonOfLars/gotgbot/commit/fd45bea9f10530a339f22f67714ea8bb38a89214

**Comment by PaulSonOfLars** [comment]
That commit doesn't change anything. I've seen this before - it's a weird error that sometimes, and that I haven't found the root cause for yet.
Only seen it happen in setwebhook though. 

If you try again, with this commit included - can you confirm it still doesn't work?

**Comment by Roker2** [comment]
I added it, I got this error again.

**Comment by Roker2** [comment]
I understood. It doesn't add "/" symbol.
Like this
https://calm-cove-01177.herokuapp.com<TOKEN>
But I need to get
https://calm-cove-01177.herokuapp.com/<TOKEN>

**Comment by Roker2** [comment]
I opened pull request.
https://github.com/PaulSonOfLars/gotgbot/pull/9
I checked https://calm-cove-01177.herokuapp.com and https://calm-cove-01177.herokuapp.com/, it works.

**Comment by PaulSonOfLars** [comment]
But now, it breaks if you use `/text` as a path.

**Comment by PaulSonOfLars** [comment]
This should now be fixed on master, as well as improved error handling to avoid similarly unhelpful errors. Let me know if there's anything else

**Comment by Roker2** [comment]
Webhook mode is working, thanks!
